name: gold_nwb
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip=23.0.1
  - pynwb=2.3.2
  - pip:
    - pyyaml==6.0
    - neuroconv[plexon,phy]==0.2.4
      # want neo==0.12.1, when available, to avoid this git silliness
    - neo @ git+https://github.com/NeuralEnsemble/python-neo.git@093231fa63781e0024aec448d8cd735ac77a42a0
    - spikeinterface[full,widgets]==0.97.1
    - probeinterface==0.2.16
    - nwbwidgets==0.10.2
    - jupyter==1.0.0
